[project]
name = "my-web-app"
version = "0.1.0"
dependencies = ["flask==2.2.5", "Werkzeug==2.2.3", "flask-cors"]

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[tool.hatch.build.targets.wheel]
packages = ["."]