name: Build Artifacts

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-windows:
    name: Build Windows
    runs-on: windows-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Ensure pip is installed
        run: |
          python -m ensurepip
          python -m pip install --upgrade pip

      - name: Run build script
        run: build_script.bat

      - name: Archive Windows artifact
        uses: actions/upload-artifact@v3
        with:
          name: windows-artifact
          path: dist/m348-jupyterlite.exe
